kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-role-binding
  namespace: poc-backstage
subjects:
  - kind: ServiceAccount
    name: backstage-sa
    namespace: poc-backstage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backstage-view-only
