kind: ServiceAccount
apiVersion: v1
metadata:
  name: backstage-sa
  namespace: poc-backstage

---  # vai facilitar
apiVersion: v1
kind: Secret
metadata:
  name: backstage-sa
  namespace: poc-backstage
  annotations:
    kubernetes.io/service-account.name: backstage-sa
type: kubernetes.io/service-account-token